# Generated by Django 5.1.3 on 2024-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
